# Generated by Django 4.1.5 on 2023-02-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True)),
                ('size', models.IntegerField(choices=[(410, 410), (473, 473), (710, 710)], default=473)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
