# Generated by Django 4.1.5 on 2023-02-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='picture',
            field=models.ImageField(null=True, upload_to='beverage_picture'),
        ),
    ]
