# Generated by Django 4.1.5 on 2023-02-08 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0003_alter_beverage_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
