# Generated by Django 4.1.5 on 2023-02-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0004_beverage_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
