# Generated by Django 4.1.5 on 2023-01-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_band', models.CharField(max_length=100, unique=True)),
                ('members', models.IntegerField()),
                ('musical_genre', models.CharField(max_length=100)),
                ('own_instruments', models.BooleanField()),
            ],
        ),
    ]
