# Generated by Django 4.1.5 on 2023-01-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_alter_band_ig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='band',
            name='ig',
        ),
    ]
