# Generated by Django 4.1.5 on 2023-01-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_band_contact_band_ig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='ig',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
