# Generated by Django 4.1.5 on 2023-01-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_alter_band_contact_alter_band_ig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='band',
            name='ig',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='band',
            name='name_band',
            field=models.CharField(max_length=100),
        ),
    ]
