# Generated by Django 4.1.5 on 2023-01-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_alter_band_contact_alter_band_ig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('band_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bands.band')),
                ('turn_assigned', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=6)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('bands.band',),
        ),
    ]
