# Generated by Django 4.1.5 on 2023-01-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='own_instruments',
        ),
        migrations.AddField(
            model_name='turn',
            name='own_instruments',
            field=models.BooleanField(default=True),
        ),
    ]
