# Generated by Django 4.1.5 on 2023-02-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_remove_band_own_instruments_turn_own_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='band_logo'),
        ),
    ]
