# Generated by Django 4.1.5 on 2023-02-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_band_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='creation_time',
            new_name='time',
        ),
    ]
