# Generated by Django 4.1.5 on 2023-02-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0011_rename_creation_time_turn_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='time',
            new_name='creation_time',
        ),
    ]
