# Generated by Django 4.1.5 on 2023-02-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0012_rename_time_turn_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='ig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='musical_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='turn_assigned',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=6, null=True),
        ),
    ]
