# Generated by Django 4.1.5 on 2023-02-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0013_alter_band_ig_alter_band_musical_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='own_instruments',
        ),
        migrations.AddField(
            model_name='band',
            name='own_instruments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
