# Generated by Django 4.1.5 on 2023-02-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0016_alter_band_own_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='name_band',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
