# Generated by Django 4.1.5 on 2023-02-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0017_alter_band_name_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer', models.ImageField(null=True, upload_to='eventos')),
            ],
        ),
    ]
