# Generated by Django 4.1.5 on 2023-02-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0019_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
